version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    ports:
      - "32306:3306"
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
      - './docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'

  php-fpm: &php
    container_name: php-fpm
    restart: always
    build:
      context: ./docker/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/loan-team

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/loan-team:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "63793:6379"

volumes:
  db-data:
    driver: local