version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - loan

  php-fpm: &php
    container_name: php-fpm
    restart: always
    build:
      context: ./docker/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/loan-team
    networks:
      - loan

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/loan-team:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - loan

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.11-management-alpine
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - loan

  mailhog:
    container_name: mailhog
    restart: always
    image: mailhog/mailhog:v1.0.1
    expose:
      - "1025"
      - "8025"
    ports:
      - "127.0.0.1:1025:8025"
    networks:
      - loan

  worker-notification:
    container_name: worker-notification
    <<: *php
    user: ${UID}:${GUID}
    command: php /var/www/loan-team/bin/console messenger:consume --time-limit=3600 async
    environment:
      - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
    ports:
      - "9005:9005"
    networks:
      - loan

networks:
  loan:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  rabbitmq-data: