version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - loan

  php-fpm: &php
    container_name: php-fpm
    restart: always
    build:
      context: ./docker/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/loan-team
    networks:
      - loan

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/loan-team:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - loan

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "63793:6379"
    networks:
      - loan

networks:
  loan:
    driver: bridge

volumes:
  mysql_data:
    driver: local